
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhowomcfclemctywhoyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRob3dvbWNmY2xlbWN0eXdob3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjM4OTIsImV4cCI6MjA1NzkzOTg5Mn0.p5nb9_6l7V824B6KE_sPqZCl3lhjGnnwfWRufMuvqTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
