
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { fromTable } from '@/services/supabase-helper';

const SUPABASE_URL = "https://dhowomcfclemctywhoyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRob3dvbWNmY2xlbWN0eXdob3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjM4OTIsImV4cCI6MjA1NzkzOTg5Mn0.p5nb9_6l7V824B6KE_sPqZCl3lhjGnnwfWRufMuvqTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
    },
  },
});

// Check if tables exist and create them if not
(async () => {
  try {
    // Check if tables have been created
    const tablesCreated = localStorage.getItem('tablesCreated');
    if (!tablesCreated) {
      console.log('Tables will be created if they don\'t exist...');

      // Use the fromTable helper to bypass TypeScript limitations
      // Products table
      const { error: productsError } = await fromTable('rpc')
        .execute('create_table_if_not_exists', { table_name: 'products' });
      if (productsError) console.error('Error creating products table:', productsError);

      // Categories table
      const { error: categoriesError } = await fromTable('rpc')
        .execute('create_table_if_not_exists', { table_name: 'categories' });
      if (categoriesError) console.error('Error creating categories table:', categoriesError);

      // Stock history table
      const { error: stockHistoryError } = await fromTable('rpc')
        .execute('create_table_if_not_exists', { table_name: 'stock_history' });
      if (stockHistoryError) console.error('Error creating stock_history table:', stockHistoryError);

      localStorage.setItem('tablesCreated', 'true');
    }

    // Check if migration has already been run
    const migrationCompleted = localStorage.getItem('migrationCompleted');
    if (!migrationCompleted) {
      console.log('Data migration will be initialized by the hook. Loading data into Supabase...');
    }
  } catch (error) {
    console.error('Error checking migration/table status:', error);
  }
})();
